# Generated by Django 2.2b1 on 2019-04-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qty', models.IntegerField()),
                ('desc', models.TextField()),
                ('photo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
